#!/bin/bash

if ! make; then 
	exit
fi

function find_ei()
{
	for f in "$*" "$*.ei" "test/$*" "test/$*.ei" ; do
		if [ -e "$f" ]; then echo $f; return; fi
	done
}

for f in "$@"; do
	src=$(find_ei $f)
	if [ -z "$src" ]; then
		echo "Cannot find '$*'" >&2
	else
		src=$(pwd)/$src
		echo $src
		pushd bin 2> /dev/null
		erl < $src
		popd 2> /dev/null
	fi
done
